"""Repository analysis foundations."""

from betterborg_cli.repo_analysis.analyzer import (
    ANALYZER_OUTPUT_SCHEMA,
    AnalyzerConfig,
    AnalyzerError,
    run_analyzer,
)
from betterborg_cli.repo_analysis.discovery import (
    DiscoveryFile,
    DiscoveryLimits,
    DiscoveryManifest,
    DiscoveryOmission,
    build_discovery_workspace,
    discovery_limits_from_mapping,
)
from betterborg_cli.repo_analysis.improvement_prds import (
    ImprovementPrd,
    generate_improvement_prds,
    resolve_theme_key,
)
from betterborg_cli.repo_analysis.prompts_manager import (
    PROMPT_MANAGER_OUTPUT_SCHEMA,
    PROMPT_ROLES,
    PromptGeneration,
    PromptManagerConfig,
    generate_role_prompts,
    get_durable_role_prompt,
)
from betterborg_cli.repo_analysis.reporting import (
    build_machine_report,
    render_json_report,
    render_markdown_report,
    render_terminal_report,
)
from betterborg_cli.repo_analysis.scoring import (
    DIMENSIONS,
    EFFORT_COST,
    RECOMMENDATION_SCHEMA,
    RECOMMENDATION_THEME_SCHEMA,
    WEIGHTS,
    PackageScore,
    RankedRecommendationTheme,
    Recommendation,
    RecommendationTheme,
    RepositoryScore,
    ScoredRecommendation,
    ThemeDimensionChange,
    compute_overall_score,
    compute_repo_overall_score,
    rank_recommendation_themes,
    score_repository,
    validate_recommendation,
    validate_recommendation_theme,
)

__all__ = [
    "ANALYZER_OUTPUT_SCHEMA",
    "AnalyzerConfig",
    "AnalyzerError",
    "DiscoveryFile",
    "DiscoveryLimits",
    "DiscoveryManifest",
    "DiscoveryOmission",
    "DIMENSIONS",
    "EFFORT_COST",
    "ImprovementPrd",
    "PackageScore",
    "PROMPT_MANAGER_OUTPUT_SCHEMA",
    "PROMPT_ROLES",
    "PromptGeneration",
    "PromptManagerConfig",
    "RECOMMENDATION_SCHEMA",
    "RECOMMENDATION_THEME_SCHEMA",
    "RankedRecommendationTheme",
    "Recommendation",
    "RecommendationTheme",
    "RepositoryScore",
    "ScoredRecommendation",
    "ThemeDimensionChange",
    "WEIGHTS",
    "build_discovery_workspace",
    "build_machine_report",
    "compute_overall_score",
    "compute_repo_overall_score",
    "discovery_limits_from_mapping",
    "generate_role_prompts",
    "get_durable_role_prompt",
    "generate_improvement_prds",
    "rank_recommendation_themes",
    "render_json_report",
    "render_markdown_report",
    "render_terminal_report",
    "resolve_theme_key",
    "run_analyzer",
    "score_repository",
    "validate_recommendation",
    "validate_recommendation_theme",
]
